# Generated by Django 4.2 on 2023-04-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0002_alter_journels_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journels',
            name='Invoice_Number',
            field=models.CharField(max_length=50),
        ),
    ]
