# Generated by Django 4.2 on 2023-04-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0004_rename_invoice_number_journels_invoicenum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journels',
            old_name='InvoiceNum',
            new_name='Invoice',
        ),
    ]
