# Generated by Django 4.2 on 2023-04-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0005_rename_invoicenum_journels_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journels',
            options={'ordering': ['Date']},
        ),
        migrations.AlterField(
            model_name='journels',
            name='Invoice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='journels',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
