# Generated by Django 4.2 on 2023-04-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0008_remove_userdetails_user_journels_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journels',
            old_name='user',
            new_name='user1',
        ),
    ]
