# Generated by Django 4.1.7 on 2023-04-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_alter_contact_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
