# Generated by Django 4.2 on 2023-05-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='process_queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.IntegerField(help_text='PK NN')),
                ('title', models.CharField(help_text='NN', max_length=200)),
                ('process_file_location', models.TextField(help_text='NN')),
                ('process_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Executed')], default=1)),
                ('return_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Success'), (3, 'Failed')], default=1)),
                ('return_json', models.TextField()),
                ('call_back_url', models.CharField(max_length=200)),
                ('call_back_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Executed')], default=1)),
                ('call_back_json', models.TextField()),
                ('process_entry_date', models.DateTimeField()),
            ],
        ),
    ]
