# Generated by Django 4.2 on 2023-05-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_id', models.IntegerField(help_text='AI,PK, NN')),
                ('category_title', models.CharField(max_length=100, unique=True)),
                ('Slug', models.CharField(max_length=100, unique=True)),
                ('Parent_category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='company_bank_accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slno', models.IntegerField(help_text='AI,PK')),
                ('BankName', models.CharField(max_length=200)),
                ('BranchName', models.CharField(max_length=200)),
                ('BranchIFSC', models.CharField(max_length=100)),
                ('Account_no', models.CharField(max_length=100)),
                ('Status', models.IntegerField(choices=[(1, 'Activate'), (0, 'Inactive')])),
                ('created_at', models.DateTimeField()),
                ('updates_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='company_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyTitle', models.CharField(max_length=255)),
                ('CompanyAddressLine1', models.CharField(max_length=255)),
                ('Website', models.CharField(max_length=255)),
                ('Contactno', models.CharField(max_length=20)),
                ('Pincode', models.IntegerField()),
                ('Post', models.CharField(max_length=255)),
                ('Logo', models.TextField()),
                ('Pancard', models.CharField(max_length=50)),
                ('RegNo', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updates_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField(help_text='AI,PK, NN')),
                ('contact_title', models.CharField(max_length=200)),
                ('contact_address_line1', models.CharField(max_length=100)),
                ('Pincode', models.IntegerField()),
                ('Contactno', models.CharField(max_length=20, unique=True)),
                ('Email', models.CharField(max_length=200)),
                ('Post', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product_attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attribute_id', models.IntegerField(help_text='AI,PK, NN')),
                ('Attribute_title', models.CharField(max_length=200)),
                ('Attribute_value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.IntegerField(help_text='AI,PK, NN')),
                ('Product_title', models.CharField(max_length=100)),
                ('Product_image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='products_suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.IntegerField(help_text='AI,PK, NN')),
                ('product_id', models.IntegerField(help_text='FK')),
                ('category_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='purchase_order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purchase_order_details_id', models.IntegerField(help_text='AI,PK, NN')),
                ('Product_id', models.IntegerField()),
                ('Unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantity', models.IntegerField()),
                ('Total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='purchase_order_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_id', models.IntegerField(help_text='AI,PK, NN')),
                ('purchase_order_date', models.DateTimeField()),
                ('purchase_order_supplier_id', models.IntegerField()),
                ('Net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SGST_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CGST_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
